version: "3"

services:
  app:
    container_name: nest_app
    build:
      context: .
      dockerfile: Dockerfile
      target: ${STAGE}
    # tag para nuestro container
    image: zero0242/nest-teslo-app:1.0.1
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"

    environment:
      PORT: ${PORT}
      HOST_URL: ${HOST_URL}
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_DURATION: ${JWT_DURATION}
  database:
    container_name: posgresdb
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_vol:
    external: false
