version: "3"

services:
  database:
    container_name: posgresdb
    image: postgres:15.1
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_vol:
    external: false
